### ISSUE TITLE
Cannot read property of undefined

### ISSUE THREAD

**Issue by camproto** [larsmars/vuejs-toggle-switch#55]
## Expected Behavior
Imports ToggleSwitch vue component

## Actual Behavior
run dev works successfully, but open the vue app in browser crashes with

Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at t (ToggleSwitch.common.js:4161:1)
    at ToggleSwitch.common.js:4265:1
    at ToggleSwitch.common.js:4658:1
    at Object.<anonymous> (ToggleSwitch.common.js:4662:1)
    at t (bootstrap c82ee93e959505698e6a:50:1)
    at Object.0 (main.js:23:1)
    at t (bootstrap c82ee93e959505698e6a:50:1)
    at window.webpackJsonp (bootstrap c82ee93e959505698e6a:21:1)
    at app.c9c6732361ce2d5c8e26.js:1:1
t @ ToggleSwitch.common.js:4161
(anonymous) @ ToggleSwitch.common.js:4265
(anonymous) @ ToggleSwitch.common.js:4658
(anonymous) @ ToggleSwitch.common.js:4662
t @ bootstrap c82ee93e959505698e6a:50
0 @ main.js:23
t @ bootstrap c82ee93e959505698e6a:50
window.webpackJsonp @ bootstrap c82ee93e959505698e6a:21
(anonymous) @ app.c9c6732361ce2d5c8e26.js:1

## Steps to Reproduce the Problem

  1. npm run dev
  2.open browser on dev server :8082
  3.white page - find above error in browser console

## Specifications

  1. "vuejs-toggle-switch": "^1.3.1"
  2."webpack": "^1.13.2",
  3."vue": "2.5.22",

This issue starts around the time you published new version 1.3.4. 

We tried with your new version 1.3.4 and got this issue in console
Uncaught SyntaxError: Cannot use import statement outside a module
    at Object.<anonymous> (app.js:864:2)
    at __webpack_require__ (app.js:556:30)
    at fn (app.js:87:20)
    at eval (eval at <anonymous> (app.js:3060:2), <anonymous>:11:19)
    at Object.<anonymous> (app.js:3060:2)
    at __webpack_require__ (app.js:556:30)
    at fn (app.js:87:20)
    at eval (eval at <anonymous> (app.js:6684:2), <anonymous>:8:19)
    at Object.<anonymous> (app.js:6684:2)
    at __webpack_require__ (app.js:556:30)

What might be changed on the old version 1.3.1?

**Comment by kirandeep123** [comment]
I am also facing the same issue but with 1.3.1 version as well.

**Comment by larsmars** [comment]
Can you upgrade to the latest version (2.0.0)? and retest?

**Comment by mtribuzio** [comment]
I have the same issue with 2.0.0 version.

**Comment by harunthuo** [comment]
@larsmars Could you kindly provide some feedback on this bug?

**Comment by harunthuo** [comment]
Rolled back to version 1.3.1 and I no longer get the bug.

**Comment by larsmars** [comment]
This should now be updated on latest release (for Vue 3). Please report back if there is still a problem 😃
